### ISSUE TITLE
KeywordOutsideEngine

### ISSUE THREAD

**Issue by TomG1993** [BernieWhite/PSDocs#118]
Hello,

Not sure this is the right place for this but I am using PSDocs along inside a powershell script to create a wiki page for azure devops. 

It had been working fine but now out of nowhere it breaks when I run: 

#region Create WIKI MarkDown Content
Write-Output "Creating mark down table for wiki"
Document 'Create-MarkdownTable' {
$date = Get-Date -UFormat "%d/%m/%Y %R"
Section Summary {
"This is the work item list for the build created:  $date"
}
Section 'Work items'{
if ($InputObject.Count -lt 1)
{
"No work items are associated"
}
foreach($item in $InputObject)
{
"#$item"
}
}
}

Specifically:

Document 'Create-MarkdownTable' {

Has anything changed to PSDocs that may have caused this.

It throws an error of:

The property 'KeywordOutsideEngine' cannot be found on this object. Verify that the property exists.
At C:\Users\tom.gorton\Documents\WindowsPowerShell\Modules\PSDocs\0.7.0\PSDocs.psm1:389 char:10
+          Write-Error -Message $LocalizedHelp.KeywordOutsideEngine -Ca ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

**Comment by BernieWhite** [comment]
@TomG1993 Thanks for the question and reporting.

The issue you are having is related to a change in the behaviour of PSDocs v0.7.0 which was recently released.

[Change log](https://github.com/BernieWhite/PSDocs/blob/main/CHANGELOG.md)

From PSDocs v0.7.0 and later, the `Document` block needs to be in a `.Doc.ps1` file and inline blocks aren't supported. This change is on purpose to support a number of additional features.

The included upgrade notes provide an example of how to address this in your code, but if you have any questions please let me know.

[Upgrade notes](https://github.com/BernieWhite/PSDocs/blob/main/docs/upgrade-notes.md)

**Comment by TomG1993** [comment]
Hi Bernie,

Let me first just say I greatly appreciate your fast response on this. PSDocs was extremely helpful in achieving my original goal so thank you for that.

Is there a way of selecting the exact version I want during the Install? I cant see an example of it if there is.

e.g. 

Install-Module -Name PSDocs -v 0.6 -Scope CurrentUser -force

Thanks for your time,

Tom
