### ISSUE TITLE
Asciidoc support

### ISSUE THREAD

**Issue by sidey79** [BernieWhite/PSDocs#157]
**Is your feature request related to a problem? Please describe.**

There are serval flavours of markdown. Using asciidoc seems to be a more clear approch for documentation, wich has some more features.

Can you support output in asciidoc format in addition of markdown?

Migrating the generated markdown always via a converter to asciidoc or include markdown direcly into markdown is maybe an alternative, but it's not sure, that the converter supports your flavor of markdown.

**Comment by BernieWhite** [comment]
@sidey79 Thanks for you feature request. I don't see why this can't be supported in the future.

**Comment by BernieWhite** [comment]
Let transfer it to discussions and see if it is also desired by the community.
