### ISSUE TITLE
Add encoding support for markdown documents instead of defaulting to ASCII

### ISSUE THREAD

**Issue by Normvariante** [BernieWhite/PSDocs#16]
I have been successfully generating markup files with this module, and started to render them with mkdocs or hugo. Yesterday I noticed that mkdocs wasn't able to render a file due to an encoding problem:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 991: invalid start byte`

I took a look at the `WriteDocumentContent` function and I found that it doesn't specify the `-Enconding` parameter of `Set-Content`: 

`$content | Set-Content -Path $Path;`

According to the documentation, [the default value for the encoding of Set-Content is ASCII](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-content?view=powershell-6#optional-parameters).

My current workaround for this is to specify the `-PassThru` parameter of `Invoke-PSDocument` and write the result to disk myself with the correct encoding:

`Invoke-PSDocument -Name Test -PassThru | Out-File -FilePath ".\result\Test.md" -Encoding utf8`

However, if the default behavior of `Invoke-PSDocument` is to write content to the disk, it should either be possible to specify the encoding, or the default encoding should not be ASCII

**Comment by BernieWhite** [comment]
@normvariante thanks for the feedback. We should default to UTF-8 since that is generally the default encoding markdown tools prefer and override by exception.

**Comment by BernieWhite** [comment]
@Normvariante master has encoding updates to support `-Encoding`

**Comment by BernieWhite** [comment]
Release with [v0.4.0](https://github.com/BernieWhite/PSDocs/releases/tag/v0.4.0)
