### ISSUE TITLE
Code blocks concatenate multiple lines

### ISSUE THREAD

**Issue by GSGBen** [BernieWhite/PSDocs#69]
**Describe the bug**
Code blocks containing multiple lines don't output multiple lines. Adding an extra line inbetween doesn't work either.

**To Reproduce**
```
        Code powershell {
            # we need to escape \ in paths in markdown
            get-childitem $PSScriptRoot | Select-Object Name,@{Name="FullName";Expression={$_.FullName -replace '\\','\\'}} | Table
        }
```
and
```
        Code powershell {
            # we need to escape \ in paths in markdown

            get-childitem $PSScriptRoot | Select-Object Name,@{Name="FullName";Expression={$_.FullName -replace '\\','\\'}} | Table
        }
```
**Expected behaviour**
Output should be
```
\```powershell
# we need to escape \ in paths in markdown
get-childitem $PSScriptRoot | Select-Object Name,@{Name="FullName";Expression={$_.FullName -replace '\\','\\'}} | Table
\```
```

(without the \\ at the start of the codefence, that's just for formatting this issue)

**Error output**
Actual output (for both) is
```
\```powershell
# we need to escape \ in paths in markdownget-childitem $PSScriptRoot | Select-Object Name,@{Name="FullName";Expression={$_.FullName -replace '\\','\\'}} | Table
\```
```

(without the \\ at the start of the codefence, that's just for formatting this issue)

**Module in use and version (please complete the following information):**
 - Module: PSDocs
 - Version: 0.6.2

**Additional context**

**Comment by BernieWhite** [comment]
@GSGBen Thanks for reporting. Yes I see the issue.

**Comment by BernieWhite** [comment]
@GSGBen I'd also take it a step further and propose that the lines breaks between lines should be preserved, as this is how code sections normally work.

**Comment by GSGBen** [comment]
> @GSGBen I'd also take it a step further and propose that the lines breaks between lines should be preserved, as this is how code sections normally work.

I agree, I should have clarified that with a second output that matches the second reproduction.
