### ISSUE TITLE
getHelp2Markdown 

### ISSUE THREAD

**Issue by ThomSwiss** [BernieWhite/PSDocs#72]
I am not able to create a markdown file from a powershell get help command.
Can you provide an example for that?

I tried to generate a markdown from
_Get-Help Format-Table_

There was not output in the markdown. With your examples from _Get-ChildItems_ ... it works.

**Comment by BernieWhite** [comment]
@ThomSwiss Thanks for you question.

As an example, it would look something like:

```powershell

Document 'CmdletHelp' {

    $cmdletHelpInfo = Get-Help -Name $InputObject;

    Title "$($cmdletHelpInfo.name[0])";

    Section 'DESCRIPTION' {
        $cmdletHelpInfo.description.Text
    }

    Section 'PARAMETERS' {
        foreach ($parameter in $cmdletHelpInfo.parameters.parameter) {
            Section $parameter.name {
                $parameter.Description.Text
            }
        }
    }

    Section 'INPUTS' {
        foreach ($inputType in $cmdletHelpInfo.inputTypes.inputType) {
            Section $inputType.type.name {
                $inputType.description.Text
            }
        }
    }

    Section 'OUTPUTS' {
        foreach ($returnValue in $cmdletHelpInfo.returnValues.returnValue) {
            Section $returnValue.type.name {
                $returnValue.description.Text
            }
        }
    }
}
```

```powershell
'format-table' | Invoke-PSDocument -Path '.\Cmdlet.doc.ps1' -Name CmdletHelp 
```

To understand the structure a bit better try `Get-Help Format-Table | ConvertTo-Json -Depth 99` and save to a file. Also you need to have help downloaded to be able to get something populated for description and parameter descriptions.

However, that said. There is another project called platyPS that generates MAML help and extracts markdown from MAML, so i'd recommend using that for you specific use case.

The structure of cmdlet help is not straight forward and there are a number of inconsistencies for generating the correct formatting for parameters, syntax, examples in markdown.

**Comment by ThomSwiss** [comment]
Thanks a lot for your good answer. I will try that.
