### ISSUE TITLE
Path not accepting whitespace

### ISSUE THREAD

**Issue by cporteou** [BernieWhite/PSDocs#87]
**Describe the bug**
When using the Invoke-PSDocument command, paths with white space are causing an error where the first part of the path is being interpreted as a cmdlet/function etc.

**To Reproduce**
Invoke-PSDocument -Path "C:\Users\username\OneDrive - Personal\subfolder" ...

**Expected behaviour**
The script should execute as normal, creating the markdown docs

**Error output**
```
VERBOSE: [Invoke-PSDocument]::BEGIN

VERBOSE: [Doc] -- Getting document definitions from: C:\Users\CraigPort\OneDrive - Company\Projects\template.doc.ps1

VERBOSE: Attempting to read: .\psdocs.yml

VERBOSE: [Doc] -- InputObject is null

VERBOSE: [Doc] -- Processing: C:\Users\CraigPort\OneDrive - Company\Projects\template.doc.ps1

Invoke-PSDocument : The term 'C:\Users\CraigPort\OneDrive' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the

path is correct and try again.

At line:1 char:1

+ Invoke-PSDocument -Path 'C:\Users\CraigPort\OneDrive - Company\Projec ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvokeDocumentException

    + FullyQualifiedErrorId : CommandNotFoundException,Invoke-PSDocument


VERBOSE: [Invoke-PSDocument]::END
```

**Module in use and version (please complete the following information):**
 - Module: PSDocs
 - Version 0.6.3

**Additional context**

**Comment by BernieWhite** [comment]
@cporteou Thanks for reporting the issue. Let me have a look. Have you tried the latest pre-release of v0.7.0?

**Comment by cporteou** [comment]
I havent tried that. Ill give it a go though and report back. Appreciate the effort btw

**Comment by BernieWhite** [comment]
@cporteou Fairly sure this is not an issue in 0.7.0. As I have a test specifically for this. But let me know if you are finding an issue.

**Comment by cporteou** [comment]
Hey, looks like 0.7.0 fixes this but I'm having trouble with using a custom function (similar to your ARM scenario usage) in that version, I get an error that it can't see the function regardless of declaring it in the doc.ps1 or importing from another file. Rolled back and both methods worked fine. Haven't tested again with 0.7.0 yet though. Thanks

**Comment by BernieWhite** [comment]
@cporteou Yes, that is a known breaking change. Helper functions need to use the `global:` scope modifier from v0.7.0. See [upgrade notes](https://github.com/BernieWhite/PSDocs/blob/main/docs/upgrade-notes.md) for an example.

**Comment by cporteou** [comment]
Hey, tried the functions with global:FUNCTIONNAME with no success I'm afraid. I'm pulling the 4 or 5 functions from another file which I load in prior to running the Invoke command. Does the import of functions need to be done inside the doc.ps1 file? It seems to work fine outside in v0.6 Thanks

**Comment by cporteou** [comment]
Think I have it working with this at the top of my .Doc.ps1 file:

`Import-module $PSScriptRoot\Functions.ps1 -Force`

**Comment by BernieWhite** [comment]
@cporteou You don't need to call `import-module` just call `Invoke-PSDocument` with a path to both files i.e. `-Path .` each file needs to use the `.Doc.ps1` extension.

**Comment by BernieWhite** [comment]
@cporteou Can this be closed?
